//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRSClient.CourseRegistrationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Registration", Namespace="http://schemas.datacontract.org/2004/07/nus.iss.crs.dm.Registration")]
    [System.SerializableAttribute()]
    public partial class Registration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DietaryRequirementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SponsorshipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CRSClient.CourseRegistrationService.RegistrationStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CRSClient.CourseRegistrationService.Billing billingInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DietaryRequirement {
            get {
                return this.DietaryRequirementField;
            }
            set {
                if ((object.ReferenceEquals(this.DietaryRequirementField, value) != true)) {
                    this.DietaryRequirementField = value;
                    this.RaisePropertyChanged("DietaryRequirement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationSize {
            get {
                return this.OrganizationSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationSizeField, value) != true)) {
                    this.OrganizationSizeField = value;
                    this.RaisePropertyChanged("OrganizationSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sponsorship {
            get {
                return this.SponsorshipField;
            }
            set {
                if ((object.ReferenceEquals(this.SponsorshipField, value) != true)) {
                    this.SponsorshipField = value;
                    this.RaisePropertyChanged("Sponsorship");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CRSClient.CourseRegistrationService.RegistrationStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CRSClient.CourseRegistrationService.Billing billingInfo {
            get {
                return this.billingInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.billingInfoField, value) != true)) {
                    this.billingInfoField = value;
                    this.RaisePropertyChanged("billingInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Billing", Namespace="http://schemas.datacontract.org/2004/07/nus.iss.crs.dm.Registration")]
    [System.SerializableAttribute()]
    public partial class Billing : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonName {
            get {
                return this.PersonNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonNameField, value) != true)) {
                    this.PersonNameField = value;
                    this.RaisePropertyChanged("PersonName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrationStatus", Namespace="http://schemas.datacontract.org/2004/07/nus.iss.crs.dm")]
    public enum RegistrationStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Valid = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancel = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/nus.iss.crs.dm.Course")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClassTime {
            get {
                return this.ClassTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassTimeField, value) != true)) {
                    this.ClassTimeField = value;
                    this.RaisePropertyChanged("ClassTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourseTitle {
            get {
                return this.CourseTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseTitleField, value) != true)) {
                    this.CourseTitleField = value;
                    this.RaisePropertyChanged("CourseTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fee {
            get {
                return this.FeeField;
            }
            set {
                if ((object.ReferenceEquals(this.FeeField, value) != true)) {
                    this.FeeField = value;
                    this.RaisePropertyChanged("Fee");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Participant", Namespace="http://schemas.datacontract.org/2004/07/nus.iss.crs.dm.Registration")]
    [System.SerializableAttribute()]
    public partial class Participant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DietaryRequirementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmploymentStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParticipantIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyIDField, value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DietaryRequirement {
            get {
                return this.DietaryRequirementField;
            }
            set {
                if ((object.ReferenceEquals(this.DietaryRequirementField, value) != true)) {
                    this.DietaryRequirementField = value;
                    this.RaisePropertyChanged("DietaryRequirement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmploymentStatus {
            get {
                return this.EmploymentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.EmploymentStatusField, value) != true)) {
                    this.EmploymentStatusField = value;
                    this.RaisePropertyChanged("EmploymentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDNumber {
            get {
                return this.IDNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IDNumberField, value) != true)) {
                    this.IDNumberField = value;
                    this.RaisePropertyChanged("IDNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationSize {
            get {
                return this.OrganizationSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationSizeField, value) != true)) {
                    this.OrganizationSizeField = value;
                    this.RaisePropertyChanged("OrganizationSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParticipantID {
            get {
                return this.ParticipantIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ParticipantIDField, value) != true)) {
                    this.ParticipantIDField = value;
                    this.RaisePropertyChanged("ParticipantID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CourseRegistrationService.ICourseRegistrationService")]
    public interface ICourseRegistrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseRegistrationService/RegistrateCourse", ReplyAction="http://tempuri.org/ICourseRegistrationService/RegistrateCourseResponse")]
        void RegistrateCourse(CRSClient.CourseRegistrationService.Registration reg, string companyName, string participantIDNumber, string courseCode, System.DateTime dateFrom, System.DateTime dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseRegistrationService/RegistrateCourse", ReplyAction="http://tempuri.org/ICourseRegistrationService/RegistrateCourseResponse")]
        System.Threading.Tasks.Task RegistrateCourseAsync(CRSClient.CourseRegistrationService.Registration reg, string companyName, string participantIDNumber, string courseCode, System.DateTime dateFrom, System.DateTime dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseRegistrationService/GetCourses", ReplyAction="http://tempuri.org/ICourseRegistrationService/GetCoursesResponse")]
        CRSClient.CourseRegistrationService.Course[] GetCourses(System.DateTime dateFrom, System.DateTime dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseRegistrationService/GetCourses", ReplyAction="http://tempuri.org/ICourseRegistrationService/GetCoursesResponse")]
        System.Threading.Tasks.Task<CRSClient.CourseRegistrationService.Course[]> GetCoursesAsync(System.DateTime dateFrom, System.DateTime dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseRegistrationService/GetEmployees", ReplyAction="http://tempuri.org/ICourseRegistrationService/GetEmployeesResponse")]
        CRSClient.CourseRegistrationService.Participant[] GetEmployees(string companyName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseRegistrationService/GetEmployees", ReplyAction="http://tempuri.org/ICourseRegistrationService/GetEmployeesResponse")]
        System.Threading.Tasks.Task<CRSClient.CourseRegistrationService.Participant[]> GetEmployeesAsync(string companyName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICourseRegistrationServiceChannel : CRSClient.CourseRegistrationService.ICourseRegistrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourseRegistrationServiceClient : System.ServiceModel.ClientBase<CRSClient.CourseRegistrationService.ICourseRegistrationService>, CRSClient.CourseRegistrationService.ICourseRegistrationService {
        
        public CourseRegistrationServiceClient() {
        }
        
        public CourseRegistrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseRegistrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseRegistrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseRegistrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegistrateCourse(CRSClient.CourseRegistrationService.Registration reg, string companyName, string participantIDNumber, string courseCode, System.DateTime dateFrom, System.DateTime dateTo) {
            base.Channel.RegistrateCourse(reg, companyName, participantIDNumber, courseCode, dateFrom, dateTo);
        }
        
        public System.Threading.Tasks.Task RegistrateCourseAsync(CRSClient.CourseRegistrationService.Registration reg, string companyName, string participantIDNumber, string courseCode, System.DateTime dateFrom, System.DateTime dateTo) {
            return base.Channel.RegistrateCourseAsync(reg, companyName, participantIDNumber, courseCode, dateFrom, dateTo);
        }
        
        public CRSClient.CourseRegistrationService.Course[] GetCourses(System.DateTime dateFrom, System.DateTime dateTo) {
            return base.Channel.GetCourses(dateFrom, dateTo);
        }
        
        public System.Threading.Tasks.Task<CRSClient.CourseRegistrationService.Course[]> GetCoursesAsync(System.DateTime dateFrom, System.DateTime dateTo) {
            return base.Channel.GetCoursesAsync(dateFrom, dateTo);
        }
        
        public CRSClient.CourseRegistrationService.Participant[] GetEmployees(string companyName) {
            return base.Channel.GetEmployees(companyName);
        }
        
        public System.Threading.Tasks.Task<CRSClient.CourseRegistrationService.Participant[]> GetEmployeesAsync(string companyName) {
            return base.Channel.GetEmployeesAsync(companyName);
        }
    }
}
