//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS_DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseClass
    {
        public string ClassID { get; set; }
        public string CourseCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string ClassCode { get; set; }
        public int Status { get; set; }
        public int Size { get; set; }
    }
}
