//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS_DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public string ParticipantID { get; set; }
        public string IDNumber { get; set; }
        public string CompanyID { get; set; }
        public string Salutation { get; set; }
        public string FullName { get; set; }
        public int Gender { get; set; }
        public string Nationality { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public string DietaryRequirement { get; set; }
        public string EmploymentStatus { get; set; }
        public string CompanyName { get; set; }
        public string JobTitle { get; set; }
        public string Department { get; set; }
        public string OrganizationSize { get; set; }
        public string SalaryRange { get; set; }
    }
}
