//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS_DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public string RegistrationID { get; set; }
        public string ClassID { get; set; }
        public string ParticipantID { get; set; }
        public int Sponsorship { get; set; }
        public string DietaryRequirement { get; set; }
        public Nullable<int> OrganizationSize { get; set; }
        public string BillingAddress { get; set; }
        public string BillingPersonName { get; set; }
        public string BillingAddressCountry { get; set; }
        public string BillingAddressPostalCode { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
